name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.x
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Python Poetry Action
      # https://github.com/marketplace/actions/python-poetry-action
      uses: abatilo/actions-poetry@v2.1.0
    - name: Lint with pylint and mypy
      run: |
        poetry run pylint statusline
        PYLINTRC=test/pylintrc poetry run pylint test
        poetry run mypy statusline test
    - name: Test with pytest
      run: |
        poetry run pytest
